development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: docheck_dev
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: docheck_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: docheck_production
  pool: 5
  timeout: 5000
